#!/bin/bash
# The script copies modified information from this directory on my laptop to rcmaster.
remote_host=$1
target=yilongl@$remote_host.utah.cloudlab.us:/shome/caladan/apps/
rsync -rtv --exclude-from=rsync-exclude.txt ./apps/shuffle $target
