#!/usr/bin/python3

# Copyright (c) 2020 Stanford University
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# This cperf benchmark computes basic latency and throughput numbers
# for Homa and TCP.

from cperf import *

parser = get_parser(description='Basic shuffle benchmark.',
        usage='%(prog)s [options]', defaults={})
options = parser.parse_args()

init(options)

#
command = "%s/%s %s --ifname %s --port %d --num-nodes %d --master-addr %s " \
          "--log-file %s" % \
          (options.shuffle_dir, options.shuffle_bin, options.caladan_cfg,
           options.ifname, options.server_port, options.num_nodes,
           options.master_addr, options.log_file)
print(command)
cluster_nodes = get_cluster_nodes(options.server_list)
cluster_nodes = cluster_nodes[:options.num_nodes]
cluster_exec(cluster_nodes, command)