#!/usr/bin/python3

# Copyright (c) 2020 Stanford University
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# This cperf benchmark computes XXX.

from cperf import *

parser = get_parser(description='Basic shuffle benchmark.',
        usage='%(prog)s [options]', defaults={})
parser.usage = parser.format_help()
options = parser.parse_args()

init(options)

nodes = range(1, options.num_nodes + 1)
if not options.plot_only:
    command = "%s/%s %s --ifname %s --num-nodes %d --master-addr %s" \
              " --log-file %s" % \
              (options.shuffle_dir, options.shuffle_bin, options.caladan_cfg,
               options.ifname, options.num_nodes, options.master_addr,
               options.log_file)
    try:
        log("Starting nodes with command:\n%s" % command)
        start_nodes(nodes, command)
        # do_cmd("tcp connect 5000", nodes)
        # do_cmd("log hello!", nodes)
        # do_cmd("udp open 5002", nodes)
        # do_cmd("gen_workload --avg-msg-size 500000 "
        #        # "--data-dist norm 100", nodes)
        #        # "--data-dist zipf 0.7 --log", nodes)
        #        "--data-dist zipf 0.7 --log", nodes)
        # do_cmd("run_bench --protocol udp --udp-port 5002 --policy GRPT --times 20", nodes)
        # do_cmd("gen_workload --avg-msg-size 50000 --data-dist zipf 4.0 --log", nodes)
        do_cmd("gen_workload --avg-msg-size 200000 --data-dist zipf 4.0 --log", nodes)
        # do_cmd("gen_workload --avg-msg-size 200000 --data-dist zipf 0.7 --log", nodes)
        # do_cmd("run_bench --protocol udp --udp-port 5002 --policy GRPF --max-payload 3600 --times 20", nodes)
        # do_cmd("run_bench --protocol udp --udp-port 5002 --policy GRPF --max-payload 3600 --no-memcpy --times 20", nodes)
        do_cmd("run_bench --protocol udp --udp-port 5002 --policy GRPF --max-payload 6000 --times 20", nodes)
        # do_cmd("run_bench --protocol udp --udp-port 5002 --policy GRPF --max-payload 6000 --no-memcpy --times 20", nodes)
        # do_cmd("run_bench --protocol tcp --policy hadoop --max-out-msgs 5 --max-seg 1400 --times 10", nodes)
        do_cmd("tt freeze", nodes)
        do_cmd("tt log", nodes)
        # do_cmd("tt print /users/yilongl/node.tt", nodes)
        log("Stopping nodes")
        stop_nodes()
    except (Exception, KeyboardInterrupt) as e:
        log("Caught exception:\n\t" + str(e))
        log("Cleaning up orphaned '%s' processes" % options.shuffle_bin)
        do_ssh(["pkill", options.shuffle_bin], nodes)
        rsync_logs()

# Parse the log files to extract useful data
# TODO: I don't have data yet